### ISSUE TITLE
Add contribution guidelines

### ISSUE THREAD

**Issue by ketch** [sbocce/hyper2D#3]
To save time, it would be very helpful if you read through what is expected for publication in JOSE and complete all the missing items, and then ping me to continue with the review.  You can see what is needed for example [here](https://github.com/openjournals/jose-reviews/issues/163).

**Comment by sbocce** [comment]
Hello, thanks a lot for your inputs & for accepting to review the submission. I'll follow your suggestions and will let you know as soon as I'm done.

**Comment by sbocce** [comment]
Hello @ketch, I have modified the paper & repository following the instructions. Here's a list of modifications and replies to the instructions.

Functionality:
- Installation -> I've introduced installation instructions in the main README and in the github wiki
- Functionality -> up to the reviewers I guess 
- Performance -> there are no claims on performance in the manuscript, so I guess this is an automatic check

Documentation:
- A statement of need -> discussed in the intro of the wiki and the README
- Installation instructions -> I've introduced a "Software requirements" section in the main README and in the github wiki
- Example usage -> there is a sample simulation in the MS (to show the functionality), please let me know if this is not enough.
- Functionality documentation -> all I have prepared on this points are wiki pages to discuss the different modules of the solver (global variables, grid, PDE, numerical solvers)
- Tests -> I have prepared **no automated tests**. Actually, I had previously submitted Hyper2D to JOSS and the reviewers kindly suggested me to submit to JOSE instead for this very reason, that there are no tests and the software is mostly educational.
- Community guidelines -> I have introduced a "Contributing and reporting bugs" section in the github wiki

Software paper
- Authors -> done
- A statement of need -> done
- References -> done

Let me know if you need some further action on my side.

**Comment by ketch** [comment]
It seems that the main documentation is the Github wiki, but I don't see how anyone would possibly know to look there, except by reading this issue thread.  Perhaps you should state in some prominent places that the wiki is the documentation, with a link.

**Comment by ketch** [comment]
I find it very strange that the package targets beginners, but doesn't give any suggestions on how to plot the output.  Your introductory text mentions "good looking fluid dynamics simulations", but your package does not produce anything "good looking", right?

Additionally, saying that the output is "a simple dat file" is not helpful, since this doesn't mean anything (at least, to me).  Is it ASCII?  Is it binary?  What is the format?  How should one read it?

**Comment by ketch** [comment]
In the installation instructions, asking the user as a first step to browse the directory structure and find one with a Makefile is okay, but not great in my opinion.  It would be much better if you listed the directory for each package in the README.
